theme: Beautiful Jekyll
title: my workout
description : my workout routine
athor: sami D
readtime: true
last-updated : 2026/01/15

# Couleurs principales
color_scheme: dark
primary_color: "#3498db" # couleur principale en hexad√©cimal
background_color: "#ffffff" # couleur de fond